version: '3.9'
services:
  backend:
    build:
      context: ./mhp/backend
    container_name: mhh-backend
    ports:
      - "5000:5000"

      
  frontend:
    build:
      context: ./mhp/frontend
    container_name: mhh-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

